"""LLM orchestration — generates 3 script variations via Groq."""

import json
from typing import List

from openai import AsyncOpenAI

from app.core.config import settings
from app.core.logger import get_logger

logger = get_logger(__name__)
_client = AsyncOpenAI(
    api_key=settings.GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1",
)

SYSTEM_PROMPT = """
You are ScriptVault — a sharp, culturally-aware script writer.
You craft real, human-sounding messages that get results.
Your output is always a JSON array of exactly 3 objects.

Rules:
1. Every script must feel WRITTEN BY A PERSON, not generated by AI.
   Avoid: hollow openers ("I hope this finds you well"), buzzwords,
   passive voice, and bullet lists where prose fits better.
2. Match the requested tone exactly.
3. Vary the 3 scripts meaningfully — different structure, angle, or hook.
4. Respect Kenyan context when relevant (local references, KES, "Sema" for casual).
5. Keep scripts concise. Cold emails ≤ 120 words. DMs ≤ 60 words.

Output format — ONLY valid JSON, no markdown:
[
  {"index": 0, "body": "...", "word_count": 42},
  {"index": 1, "body": "...", "word_count": 38},
  {"index": 2, "body": "...", "word_count": 45}
]
"""


def _build_user_prompt(intent: str, tone: str, context: str) -> str:
    return (
        f"Intent: {intent.replace('_', ' ').title()}\n"
        f"Tone: {tone.replace('_', ' ').title()}\n"
        f"Context: {context}\n\n"
        "Generate 3 variations. Output ONLY the JSON array."
    )


async def generate_script_variations(intent: str, tone: str, context: str) -> List[dict]:
    user_prompt = _build_user_prompt(intent, tone, context)
    try:
        response = await _client.chat.completions.create(
            model=settings.GROQ_MODEL,
            temperature=settings.GROQ_TEMPERATURE,
            max_tokens=settings.GROQ_MAX_TOKENS,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        )
        raw = response.choices[0].message.content or "[]"
        parsed = json.loads(raw)
        if isinstance(parsed, dict):
            for v in parsed.values():
                if isinstance(v, list):
                    parsed = v
                    break
        variations = []
        for item in parsed[:3]:
            body = item.get("body", "").strip()
            variations.append({
                "index": item.get("index", len(variations)),
                "body": body,
                "word_count": len(body.split()),
            })
        return variations
    except Exception as exc:
        logger.error(f"Groq generation failed: {exc}")
        if settings.ENV == "production":
            raise
        logger.warning("Returning stub variations (dev mode).")
        stub = f"[Dev stub] Reaching out about: {context[:40]}..."
        return [{"index": i, "body": f"Variation {i + 1}: {stub}", "word_count": 12} for i in range(3)]
